import React from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Download, Search, Trash2 } from "lucide-react";

const ReportsTable = ({ 
    reports, 
    role, 
    onDownload,
    onDelete,
    onVisibilityChange
}) => {
    
    if (reports.length === 0) {
        return (
            <div className="bg-white rounded-3xl p-16 text-center border border-[#0F172A]/5 shadow-sm">
                <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-slate-50 text-slate-400 mb-6">
                    <Search size={32} />
                </div>
                <h3 className="text-xl font-black text-[#0F172A] mb-2">No Reports Found</h3>
                <p className="text-[#0F172A]/50 font-medium">Try adjusting your search criteria or filters.</p>
            </div>
        );
    }

    return (
        <div className="bg-white rounded-3xl border border-[#0F172A]/5 shadow-sm overflow-hidden">
            <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                    <thead>
                        <tr className="bg-slate-50/50 border-b border-slate-100/80">
                            <th className="py-4 px-6 text-[10px] font-black uppercase tracking-widest text-[#0F172A]/40 whitespace-nowrap">Report Details</th>
                            <th className="py-4 px-6 text-[10px] font-black uppercase tracking-widest text-[#0F172A]/40 whitespace-nowrap">Report Type</th>
                            <th className="py-4 px-6 text-[10px] font-black uppercase tracking-widest text-[#0F172A]/40 whitespace-nowrap">Generated By</th>
                            <th className="py-4 px-6 text-[10px] font-black uppercase tracking-widest text-[#0F172A]/40 whitespace-nowrap">Created At</th>
                            <th className="py-4 px-6 text-[10px] font-black uppercase tracking-widest text-[#0F172A]/40 whitespace-nowrap text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100/80">
                        <AnimatePresence>
                            {reports.map((report) => (
                                <motion.tr 
                                    key={report.id}
                                    layout
                                    initial={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    exit={{ opacity: 0 }}
                                    className="group hover:bg-slate-50/30 transition-colors"
                                >
                                    <td className="py-5 px-6">
                                        <div className="font-bold text-[#0F172A] mb-1">
                                            {report.reportTitle}
                                        </div>
                                        <div className="text-[10px] font-bold text-slate-400 mt-1 flex gap-3">
                                            {report.startDate && report.endDate && <span>Range: {report.startDate} to {report.endDate}</span>}
                                            {!report.startDate && <span>Snapshot Report</span>}
                                        </div>
                                    </td>
                                    
                                    <td className="py-5 px-6">
                                        <span className="bg-[#007A5E]/10 text-[#007A5E] px-3 py-1 rounded-full text-xs font-bold">
                                            {report.reportType}
                                        </span>
                                    </td>

                                    <td className="py-5 px-6">
                                        <div className="text-sm font-semibold text-[#0F172A]/80">
                                            {report.createdBy}
                                        </div>
                                    </td>

                                    <td className="py-5 px-6">
                                        <div className="text-sm font-semibold text-[#0F172A]/60">
                                            {new Date(report.createdAt).toLocaleString()}
                                        </div>
                                    </td>

                                    <td className="py-5 px-6">
                                        <div className="flex items-center justify-end gap-2">
                                            {role === "ADMIN" && (
                                                <select 
                                                    value={report.visibility || "ADMIN"}
                                                    onChange={(e) => onVisibilityChange && onVisibilityChange(report.id, e.target.value)}
                                                    className="py-1 px-2 rounded bg-slate-100 text-xs font-bold text-[#0F172A]/70 outline-none border-none cursor-pointer hover:bg-slate-200"
                                                    title="Change Visibility"
                                                >
                                                    <option value="ADMIN">Admin Only</option>
                                                    <option value="STAFF">Staff</option>
                                                    <option value="ALL">All</option>
                                                </select>
                                            )}
                                            
                                            <button 
                                                onClick={() => onDownload(report)}
                                                className="w-8 h-8 rounded-xl bg-slate-50 text-[#0F172A] hover:bg-[#007A5E] hover:text-white flex items-center justify-center transition-all group-hover:shadow-sm"
                                                title="Download PDF"
                                            >
                                                <Download size={16} />
                                            </button>
                                            
                                            {role === "ADMIN" && onDelete && (
                                                <button 
                                                    onClick={() => onDelete(report.id)}
                                                    className="w-8 h-8 rounded-xl bg-slate-50 text-slate-400 hover:bg-red-500 hover:text-white flex items-center justify-center transition-all group-hover:shadow-sm"
                                                    title="Delete Report"
                                                >
                                                    <Trash2 size={16} />
                                                </button>
                                            )}
                                        </div>
                                    </td>
                                </motion.tr>
                            ))}
                        </AnimatePresence>
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default ReportsTable;
