import React from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Eye, Download, Calendar, User, FileText, Activity, Hash, Tag } from "lucide-react";
import { ReportStatusBadge, ReportPriorityBadge } from "./ReportStatusBadge";

const ReportPreviewModal = ({ report, onClose, onDownload }) => {
    if (!report) return null;

    return (
        <AnimatePresence>
            <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-[#0F172A]/40 backdrop-blur-sm"
                onClick={onClose}
            >
                <motion.div 
                    initial={{ opacity: 0, scale: 0.95, y: 20 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95, y: 20 }}
                    className="bg-white rounded-[2rem] shadow-2xl w-full max-w-3xl overflow-hidden border border-white/20 relative flex flex-col max-h-[90vh]"
                    onClick={e => e.stopPropagation()}
                >
                    <div className="p-8 border-b border-slate-100 flex items-start justify-between bg-slate-50/50">
                        <div>
                            <div className="flex items-center gap-3 mb-3">
                                <ReportStatusBadge status={report.status} />
                                <ReportPriorityBadge priority={report.priority} />
                                {report.published && (
                                    <span className="px-2 py-0.5 rounded-md bg-[#007A5E]/10 text-[#007A5E] text-[10px] font-black uppercase tracking-widest border border-[#007A5E]/20">
                                        Published
                                    </span>
                                )}
                            </div>
                            <h2 className="text-3xl font-black text-[#0F172A]">{report.reportTitle}</h2>
                            <p className="text-[#0F172A]/50 mt-2 font-medium flex items-center gap-2">
                                <Tag size={14}/> {report.reportType}
                            </p>
                        </div>
                        <button 
                            onClick={onClose}
                            className="w-10 h-10 rounded-full bg-white border border-slate-200 flex items-center justify-center text-slate-400 hover:text-[#0F172A] hover:bg-slate-50 transition-all"
                        >
                            <X size={20} />
                        </button>
                    </div>

                    <div className="p-8 overflow-y-auto flex-1">
                        <div className="grid md:grid-cols-2 gap-8 mb-8">
                            <div>
                                <h4 className="text-[10px] font-black uppercase tracking-widest text-[#0F172A]/40 mb-3 flex items-center gap-2"><FileText size={12}/> Executive Summary</h4>
                                <p className="text-sm font-medium text-[#0F172A]/70 leading-relaxed bg-slate-50 p-4 rounded-2xl border border-slate-100">
                                    {report.description || "No description provided."}
                                </p>
                                
                                {report.notes && (
                                    <div className="mt-4">
                                        <h4 className="text-[10px] font-black uppercase tracking-widest text-[#0F172A]/40 mb-2">Internal Notes</h4>
                                        <div className="text-sm font-medium text-[#0F172A]/70 p-4 rounded-2xl bg-yellow-50/50 border border-yellow-100/50">
                                            {report.notes}
                                        </div>
                                    </div>
                                )}
                            </div>
                            
                            <div className="space-y-4">
                                <div className="bg-slate-50 rounded-2xl p-4 border border-slate-100 flex items-center justify-between">
                                    <div className="flex items-center gap-3 text-sm font-bold text-[#0F172A]"><Calendar size={16} className="text-[#0F172A]/40"/> Date Range</div>
                                    <div className="text-sm font-medium text-[#0F172A]/60">{report.dateRangeStart || "N/A"} to {report.dateRangeEnd || "N/A"}</div>
                                </div>
                                <div className="bg-slate-50 rounded-2xl p-4 border border-slate-100 flex items-center justify-between">
                                    <div className="flex items-center gap-3 text-sm font-bold text-[#0F172A]"><User size={16} className="text-[#0F172A]/40"/> Generated By</div>
                                    <div className="text-sm font-medium text-[#0F172A]/60">{report.generatedBy}</div>
                                </div>
                                <div className="bg-slate-50 rounded-2xl p-4 border border-slate-100 flex items-center justify-between">
                                    <div className="flex items-center gap-3 text-sm font-bold text-[#0F172A]"><Activity size={16} className="text-[#0F172A]/40"/> Generated Date</div>
                                    <div className="text-sm font-medium text-[#0F172A]/60">{report.generatedDate || "Pending"}</div>
                                </div>
                                <div className="bg-slate-50 rounded-2xl p-4 border border-slate-100 flex items-center justify-between">
                                    <div className="flex items-center gap-3 text-sm font-bold text-[#0F172A]"><Hash size={16} className="text-[#0F172A]/40"/> Report ID</div>
                                    <div className="text-sm font-medium text-[#0F172A]/60">{report.id}</div>
                                </div>
                                <div className="bg-slate-50 rounded-2xl p-4 border border-slate-100 flex items-center justify-between">
                                    <div className="flex items-center gap-3 text-sm font-bold text-[#0F172A]">Visibility</div>
                                    <div className="text-sm font-medium text-[#0F172A]/60 px-2 py-1 bg-white border border-slate-200 rounded-md">{report.visibility}</div>
                                </div>
                            </div>
                        </div>

                        {report.status === "Generated" || report.status === "Published" ? (
                            <div className="rounded-2xl border-2 border-dashed border-slate-200 p-8 text-center bg-slate-50/50">
                                <div className="w-16 h-16 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center mx-auto mb-4">
                                    <Eye size={24} />
                                </div>
                                <h3 className="text-lg font-black text-[#0F172A] mb-2">Report Content Ready</h3>
                                <p className="text-sm font-medium text-[#0F172A]/60 mb-6 max-w-xs mx-auto">
                                    This report is fully compiled. You can export the detailed content in {report.format} format.
                                </p>
                                <button 
                                    onClick={() => onDownload(report)}
                                    className="px-6 py-3 rounded-xl bg-[#007A5E] text-white text-sm font-bold shadow-lg shadow-[#007A5E]/20 hover:scale-105 active:scale-95 transition-all inline-flex items-center gap-2"
                                >
                                    <Download size={18} /> Download {report.format}
                                </button>
                            </div>
                        ) : (
                            <div className="rounded-2xl border-2 border-dashed border-slate-200 p-8 text-center bg-slate-50/50">
                                <div className="w-16 h-16 rounded-full bg-slate-200 text-slate-400 flex items-center justify-center mx-auto mb-4">
                                    <Clock size={24} />
                                </div>
                                <h3 className="text-lg font-black text-[#0F172A] mb-2">Data Pending</h3>
                                <p className="text-sm font-medium text-[#0F172A]/60 max-w-xs mx-auto">
                                    This report is currently in {report.status} state. Data will be viewable once it is marked as Generated.
                                </p>
                            </div>
                        )}
                    </div>
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
};

export default ReportPreviewModal;
